#后端端口号
server:
  port: 9090
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/kelvihan?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

#配置Mybatis实体和xml映射
mybatis:
  ##映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置日志:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true